SELECT 
    f.[FECHA_DESEMBOLSO],
    DATEPART(WEEKDAY, f.[FECHA_DESEMBOLSO]) AS DIA,
    MONTH(f.[FECHA_DESEMBOLSO]) as MES,
    f.[TIPO_PAGO],
    b.[BANCA],
    f.[TIPO_CREDITO],
    f.[TIPO_CLIENTE],
    SUM(f.[MONTO_DESEMBOLSADO]) AS MONTO_COLOCADO,
    SUM(f.[DESEMBOLSO_NETO]) AS NETO_COLOCADO
FROM [CRECIMIENTO].[FACT_COSECHAS_CARTERA_FIDUCIARIA] f
LEFT JOIN [CRECIMIENTO].[DIM_BANCA] b 
    ON f.[CODIGO_BANCA_ASIGNACION] = b.[CODIGO_BANCA_ASIGNACION]
WHERE f.[ESTADO_CREDITO] = 'D'
  AND f.[FECHA_DESEMBOLSO] BETWEEN '2022-01-01' AND '2024-12-31'
GROUP BY 
    f.[FECHA_DESEMBOLSO],
    f.[TIPO_PAGO],
    b.[BANCA],
    f.[TIPO_CREDITO],
    f.[TIPO_CLIENTE],
    DATEPART(WEEKDAY, f.[FECHA_DESEMBOLSO])
ORDER BY f.[FECHA_DESEMBOLSO];

  

--[FEC_SALDO]
--,f.[TIPO_COSECHA]
--,f.[MARGEN_FINANCIERO]
--,f.[SALDO_CARTERA]
--,[ES_RECREDITO]
--,f.[TASA_COSECHA] AS TASA
--,[ES_OFERTA_SELECCIONADA]
--,f.[PLAZO_MESES_COSECHA]
--,[CODIGO_PRODUCTO]
--,[CODIGO_BANCA_ASIGNACION]
--,[TIPO_PROMOCION_CREDITO]
--,[PRIORIZACION_TIPO_COSECHA]
--,[SUB_AGRUPADOR_COSECHA]
--,[AGRUPADOR_COSECHA]
--[CODIGO_CLIENTE]
--[ESTADO_SALDO]
--,[ESTADO_CREDITO]
--,[FECHA_APERTURA]
--[ES_CLIENTE_BANCO_INDUSTRIAL]
--,[CONSOLIDACION_BANCO_INDUSTRIAL]
--,[FLAG_FOCO_BANCO_INDUSTRIAL]
--[ES_INCUMPLIMIENTO_POR_CANCELACION]
--,[CODIGO_EJECUTIVO_LABOR]
--,[GRUPO_CLIENTE_BIENESTAR]
--,[GRUPO_BIENESTAR_PRODUCTO]
--,[FLAG_RCI_HASTA_60_PLAZO_144]
--,[FLAG_RCI_HASTA_60_PLAZO_DIF_144]
--,[FLAG_MONTOS_ALTOS]
--,[FLAG_FOCO_BANRURAL]
--,[FLAG_ADULTO_MAYOR]
--,[FLAG_SCORE_MENOR_420]
--,[FLAG_RETENCION_REACTIVA]
--,[FLAG_RETENCION_PROACTIVA]
--,[FLAG_BANCONSEJOS]
--,[FLAG_EXCEPCIONES]
--,[FLAG_CREDITO_PLUS]
--,[CANCELACION_POR_RECREDITO]
--,[CUOTA_MENSUAL_PROYECTADA]
--,f.[FLAG_PAGO_VOLUNTARIO]
--,[PRODUCTO_FINANCIERO_ANUAL]
--,[FLAG_BIENESTAR]
--,[FLAG_CANAL_EMPLEADO]
--,[CANTIDAD_MESES_ULTIMO_SALDO]
--,[FACTOR_TASA_PP_COSECHA]
--,[FACTOR_PLAZO_PP_COSECHA]
--,[TPP_VISION_CLIENTE]
--,[MONTO_OFERTA_SELECCIONADA]
--,[PLAZO_OFERTA_SELECCIONADA]
--,[TASA_MESES]
--,[CONSOLIDACION_SALDO_CREDITOS_EXTERNOS]
--,[CONSOLIDACION_SALDO_TC_EXTERNOS]
--,[CONSOLIDACION_FACTORAJE_EXTERNOS]
--,[CONSOLIDACION_SALDO_CREDITO_BANTRAB]
--,[CONSOLIDACION_SALDO_TC_BANTRAB]
--,[TPP_VISION_CLIENTE_CANCELACION]
--,[CODIGO_SUB_SEGMENTO]
--,[CODIGO_PATRONO]
--,[CUOTA_PRESTAMO_BANTRAB_INTERNO]
--,[CUOTA_TOTAL_CLIENTE_INTERNO]
--,[CUOTA_PRESTAMOS_CLIENTE_EXTERNO]
--,[CUOTA_TOTAL_CLIENTE_EXTERNO]
--,[ORIGEN_PRECALIFICACION]
--,[LATITUD_PRECALIFICACION]
--,[LONGITUD_PRECALIFICACION]
--,[CODIGO_CENTRO_NEGOCIO]
--,[ES_CLIENTE_CREDITO_PLUS]
--,[ES_CLIENTE_BANRURAL]
--,[CONSOLIDACION_BANRURAL]
--,[SCORE_TUCA]
--,[CLASIFICACION_SCORE_TUCA]
--,[SCORE_FICO]
--,[QUINTIL_RIESGO]
--,[ESTADO_COLOR]
--,[RCI_INTERNO_INICIAL_DEUDOR]
--,[RCI_INTERNO_FINAL_DEUDOR]
--,[RCI_GLOBAL_INICIAL_DEUDOR]
--,[RCI_GLOBAL_FINAL_DEUDOR]
--,[INGRESOS_CLIENTE]
--,[EDAD]
--,[FECHA_REGISTRO_PRECALIFICACION]
--,[NO_PRECALIFICACION]
--,[NUMERO_SOLICITUD]
